---
pre_date_shift_for_assignment_importing:
  state: hidden
  display_name: Pre-Date Shift for Assignment importing
  description: |-
    This feature flag enables the assignment and classic quiz creation with shifted dates during content migration.
    The original flow perform date shifting after the assignment creation as an update operation.
  applies_to: SiteAdmin
